/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MdButtonFlat {
    'text': string;
  }
  interface MdDialog {}
  interface MdDialogFooter {}
  interface MdDialogHeader {
    'title': string;
  }
}

declare global {


  interface HTMLMdButtonFlatElement extends Components.MdButtonFlat, HTMLStencilElement {}
  var HTMLMdButtonFlatElement: {
    prototype: HTMLMdButtonFlatElement;
    new (): HTMLMdButtonFlatElement;
  };

  interface HTMLMdDialogElement extends Components.MdDialog, HTMLStencilElement {}
  var HTMLMdDialogElement: {
    prototype: HTMLMdDialogElement;
    new (): HTMLMdDialogElement;
  };

  interface HTMLMdDialogFooterElement extends Components.MdDialogFooter, HTMLStencilElement {}
  var HTMLMdDialogFooterElement: {
    prototype: HTMLMdDialogFooterElement;
    new (): HTMLMdDialogFooterElement;
  };

  interface HTMLMdDialogHeaderElement extends Components.MdDialogHeader, HTMLStencilElement {}
  var HTMLMdDialogHeaderElement: {
    prototype: HTMLMdDialogHeaderElement;
    new (): HTMLMdDialogHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'md-button-flat': HTMLMdButtonFlatElement;
    'md-dialog': HTMLMdDialogElement;
    'md-dialog-footer': HTMLMdDialogFooterElement;
    'md-dialog-header': HTMLMdDialogHeaderElement;
  }
}

declare namespace LocalJSX {
  interface MdButtonFlat extends JSXBase.HTMLAttributes<HTMLMdButtonFlatElement> {
    'text'?: string;
  }
  interface MdDialog extends JSXBase.HTMLAttributes<HTMLMdDialogElement> {}
  interface MdDialogFooter extends JSXBase.HTMLAttributes<HTMLMdDialogFooterElement> {}
  interface MdDialogHeader extends JSXBase.HTMLAttributes<HTMLMdDialogHeaderElement> {
    'title'?: string;
  }

  interface IntrinsicElements {
    'md-button-flat': MdButtonFlat;
    'md-dialog': MdDialog;
    'md-dialog-footer': MdDialogFooter;
    'md-dialog-header': MdDialogHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


